# -*- restclient -*-
#

##
GET http://localhost:28888/help
User-Agent: Emacs Restclient

##
GET http://localhost:28888/actuator/conn_info?conn_id=1
User-Agent: Emacs Restclient

##
GET http://localhost:28888/actuator/conn_tags?conn_id=1&namespace=snitch
User-Agent: Emacs Restclient

##
GET http://localhost:28888/actuator/tag_conns?namespace=snitch&key=uid&val=1
User-Agent: Emacs Restclient

#
# Post Example
#
POST https://jira.atlassian.com/rest/api/2/search
Content-Type: application/json

{
        "jql": "project = HSP",
        "startAt": 0,
        "maxResults": 15,
        "fields": [
                "summary",
                "status",
                "assignee"
        ]
}